# Generated by Django 5.0.7 on 2024-07-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Noodle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("recommendation", models.BooleanField()),
                (
                    "country_id",
                    models.ForeignKey(
                        default="Страна неизвестна",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="main_app.country",
                    ),
                ),
                (
                    "manufacturer_id",
                    models.ForeignKey(
                        default="Производитель неизвестен",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="main_app.manufacturer",
                    ),
                ),
            ],
        ),
    ]
