# Generated by Django 5.0.7 on 2024-10-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_alter_country_name_alter_manufacturer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Страна"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Производитель"
            ),
        ),
    ]
